default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db

development:
  <<: *default
  database: moip-technical-challenge_development

test:
  <<: *default
  database: moip-technical-challenge_test

production:
  <<: *default
  database: moip-technical-challenge_production
